[tool.poetry]
name = "tic-tac-toe"
version = "0.1.0"
description = ""
authors = ["wojciech.kaminski <wojtek.kamlot@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
